import type { ModuleDefinition, Field } from '@/types/common';
const f = (
  key: string,
  kind: Field['kind'] = 'text',
  required = false,
  options?: string[],
): Field => ({ key, kind, required, options });
export const departments = [
  'Front Office',
  'Housekeeping',
  'Food & Beverage',
  'Engineering',
  'Human Resources',
  'Finance',
];
export const departmentWorkSchedules: Record<string, string> = {
  'Front Office': 'rotatingSchedule',
  Housekeeping: 'rotatingSchedule',
  'Food & Beverage': 'rotatingSchedule',
  Engineering: 'rotatingSchedule',
  'Human Resources': 'administrativeSchedule',
  Finance: 'administrativeSchedule',
};
export const positions = [
  'Manager',
  'Supervisor',
  'Receptionist',
  'Room Attendant',
  'Chef',
  'Accountant',
];
const base = [
  f('code', 'text', true),
  f('name', 'text', true),
  f('department', 'select', true, departments),
];
const status = f('status', 'select', true, ['active', 'pending', 'draft', 'expired']);
export const modules: ModuleDefinition[] = [
  {
    key: 'tuyen-dung',
    icon: 'pi-user-plus',
    group: 'people',
    columns: [
      'code',
      'name',
      'phone',
      'email',
      'department',
      'position',
      'startDate',
      'income',
      'status',
    ],
    fields: [
      ...base,
      f('phone'),
      f('email', 'email'),
      f('position', 'select', true, positions),
      f('gender', 'select', true, ['Nam', 'Nữ', 'Khác']),
      f('startDate', 'date'),
      f('income', 'number', true),
      f('salary', 'number', true),
      f('probationSalary', 'number', true),
      f('status', 'select', true, ['recruiting', 'receiving', 'rejected', 'declined', 'onboarded']),
    ],
  },
  {
    key: 'contracts',
    icon: 'pi-file-edit',
    group: 'people',
    columns: [
      'code',
      'employeeId',
      'name',
      'department',
      'position',
      'type',
      'signingDate',
      'startDate',
      'endDate',
      'salary',
      'income',
      'status',
    ],
    fields: [
      ...base,
      f('employeeId', 'text', true),
      f('position', 'select', true, positions),
      f('type', 'select', true, ['fixed', 'permanent', 'probation']),
      f('signingDate', 'date', true),
      f('startDate', 'date', true),
      f('endDate', 'date'),
      f('salary', 'number', true),
      f('income', 'number', true),
      status,
    ],
    detailTabs: ['information', 'compensation', 'allowances', 'history', 'documents'],
  },
  {
    key: 'employees',
    icon: 'pi-users',
    group: 'people',
    columns: [
      'code',
      'name',
      'gender',
      'birthDate',
      'department',
      'position',
      'startDate',
      'type',
      'status',
    ],
    fields: [
      ...base,
      f('position', 'select', true, positions),
      f('gender', 'select', false, ['Nam', 'Nữ', 'Khác']),
      f('birthDate', 'date'),
      f('identityNumber'),
      f('address'),
      f('phone'),
      f('email', 'email', true),
      f('emergencyContact'),
      f('education'),
      f('bank'),
      f('bankAccount'),
      f('taxNumber'),
      f('insuranceNumber'),
      f('healthInsuranceNumber'),
      f('healthcareProvider'),
      f('hotel'),
      f('subDepartment'),
      f('grade'),
      f('manager'),
      f('shiftPattern', 'select', false, ['Ca xoay 3 ca', 'Hành chính', 'Ca gãy']),
      f('probationSalary', 'number'),
      f('serviceChargeRate', 'number'),
      f('type', 'select', true, ['fixed', 'permanent', 'probation']),
      f('salary', 'number'),
      f('startDate', 'date', true),
      status,
    ],
    detailTabs: [
      'personal',
      'employment',
      'contracts',
      'insurance',
      'schedules',
      'attendance',
      'leave',
      'overtime',
      'payroll',
      'documents',
      'history',
    ],
  },
  {
    key: 'departments',
    icon: 'pi-sitemap',
    group: 'people',
    columns: ['code', 'name', 'workSchedule', 'hod', 'count', 'status'],
    fields: [
      f('code', 'text', true),
      f('name', 'text', true),
      f('workSchedule', 'select', true, ['administrativeSchedule', 'rotatingSchedule']),
      f('hod'),
      f('count', 'number'),
      status,
    ],
  },
  {
    key: 'positions',
    icon: 'pi-briefcase',
    group: 'people',
    columns: ['code', 'name', 'department', 'status'],
    fields: [...base, status],
    detailTabs: ['information', 'employees', 'contracts'],
  },
  ...['contract-types', 'allowance-types'].map((key) => ({
    key,
    icon: 'pi-tags',
    group: 'people',
    columns: ['code', 'name', 'status'],
    fields: [f('code', 'text', true), f('name', 'text', true), status],
  })),
  ...['attendance', 'schedules', 'leave', 'overtime', 'night-shift'].map((key) => ({
    key,
    icon: key === 'schedules' ? 'pi-calendar' : 'pi-clock',
    group: 'operations',
    columns: [
      'code',
      'name',
      'department',
      'date',
      key === 'leave' ? 'days' : 'hours',
      'shift',
      'status',
    ],
    fields: [
      ...base,
      f('date', 'date', true),
      f(key === 'leave' ? 'days' : 'hours', 'number', true),
      f('shift', 'select', false, ['06:00–14:00', '14:00–22:00', '22:00–06:00']),
      f('note', 'textarea'),
      status,
    ],
  })),
  ...['payroll', 'insurance', 'pit', 'service-charge', 'reports'].map((key) => ({
    key,
    icon: key === 'reports' ? 'pi-chart-bar' : 'pi-wallet',
    group: 'finance',
    columns: ['code', 'name', 'department', 'period', 'amount', 'status'],
    fields: [
      ...base,
      f('period', 'text', true),
      f('amount', 'number', true),
      f('note', 'textarea'),
      status,
    ],
  })),
];
export const getModule = (key: string) => modules.find((m) => m.key === key)!;
